### ISSUE TITLE
move `Types.mo` from `internal` to `src` so Mops can generate docs

### ISSUE THREAD

**Issue by ZenVoich** [edjCase/motoko_datetime#5]
For example, it is hard to see what possible values of `DayOfWeek`  on https://mops.one/datetime/docs#type.DayOfWeek

**Comment by Gekctek** [comment]
Any thoughts on good ways of fixing this without a manual duplication for each one?
I need the types in another file or I would have to restructure my project, would have to think of how.

I guess maybe is another approach and see if I can put in a request to change the motoko documentation generator to always show the referenced type?

**Comment by ZenVoich** [comment]
The main problem is that we cannot find docs for `Types.mo` file
<img width="301" alt="image" src="https://github.com/edjCase/motoko_datetime/assets/21315978/dfeea083-5440-4dbf-a070-5d63d4d7e9c6">
If yout move `Types.mo` to `src` folder it will appear in the left panel.

**Comment by Gekctek** [comment]
Ill do that at least as a temporary measure
I put in an issue to see if there are other solutions
https://github.com/dfinity/motoko/issues/4290

**Comment by Gekctek** [comment]
Fixed with version 0.1.2
https://mops.one/datetime/docs/Types
